### ISSUE TITLE
UmbracoSupport class errors

### ISSUE THREAD

**Issue by ismailmayat** [lars-erik/umbraco-unit-testing-samples#1]
I am using umbraco 7.7.0 and utilising the UmbracoSupport class in my test project.  I cannot compile i get following errors:

Error	CS1729	'PublishedContentModelFactoryResolver' does not contain a constructor that takes 1 arguments	
Error	CS1729	'PropertyValueConvertersResolver' does not contain a constructor that takes 3 arguments
Error	CS0122	'ActivatorServiceProvider' is inaccessible due to its protection level	
Error	CS0117	'PublishedContentType' does not contain a definition for 'GetPublishedContentTypeCallback'

I thought according to readme I should have access to internal methods?

**Comment by lars-erik** [comment]
You need the exact same version of Umbraco.Tests as Core to ensure compatibility, and you need UmbracoSupport to be in an assembly called Umbraco.UnitTesting.Adapter or Umbraco.VisualStudio to get access to internals.

There's also the off chance I've fixed this in my workshop material and forgot to do it here. The code is over here:  
https://bitbucket.org/bleedo/umbraco-testing-workshop-h2-2017/src/ee85bd0953edec03d26d4e35e1ca5e8644ac4863/Umbraco.UnitTesting.Adapter/Support/UmbracoSupport.cs?at=master&fileviewer=file-view-default  
https://bitbucket.org/bleedo/umbraco-testing-workshop-h2-2017/src/ee85bd0953edec03d26d4e35e1ca5e8644ac4863/Umbraco.UnitTesting.Adapter/Support/FakeTypedModelFactory.cs?at=master&fileviewer=file-view-default

**Comment by ismailmayat** [comment]
That worked cheers.
